// Module included in the following assemblies:
//
// * osd_install_access_delete_cluster/creating-a-gcp-cluster-with-workload-identity-federation.adoc


:_mod-docs-content-type: CONCEPT
[id="service-account-auth-overview_{context}"]
= Service Account authorization overview

The Service Account authorization type requires the creation of a private key of an IAM service account called `osd-ccs-admin`, which authenticates with Google Cloud services.
Service account authentication requires managing service account keys which can be a security risk if not handled properly.
[IMPORTANT]
=====
Red Hat recommends using GCP Workload Identity Federation (WIF) as the authentication type for installing and interacting with the OpenShift Dedicated cluster deployed on Google Cloud Platform (GCP) because it provides enhanced security. For more information, see  the topic xref:../osd_install_access_delete_cluster/creating-a-gcp-cluster-with-workload-identity-federation.adoc#osd-creating-a-cluster-on-gcp-with-workload-identity-federation[Creating a cluster on GCP with Workload Identity Federation authentication].
=====